spring:
  jpa:
    hibernate.ddl-auto: create-drop
    hibernate.generate-ddl: true
    hibernate.show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      connection.useUnicode: true
      connection.characterEncoding: UTF-8
 
  datasource:
    username: zorbeez
    password: zorbeez
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/zorbeez?createDatabaseIfNotExist=true     
