spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.connection.useUnicode: true
      hibernate.connection.characterEncoding: UTF-8
 
  datasource:
    username: zorbeez
    password: zorbeez
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/zorbeez?createDatabaseIfNotExist=true     

logging:
  level:
    org.org.springframework: ERROR
    com.sitdh.thesis.core: DEBUG